package test
import com.genscript.gsscm.rule.fact.*
import com.genscript.gsscm.rule.fact.point.*
import com.genscript.gsscm.rule.fact.price.*

dialect  "mvel"

rule "Get Lastest Version for SC1010"
    when
        $f : PriceFact(catalogNo == 'SC1010')
    then
    	System.out.println("Get Lastest Version for SC1010")
        $f.setVersion("v20160426")
end


rule "Get Lastest Version for Point"
    when
        $f : PointFact()
    then
    	System.out.println("Get Lastest Version for Point")
        $f.setVersion("v20160426")
end
